all:

edit:
	gvim -o abc-path.js abc-path-test.js ../Games-ABC_Path-Generator/t/ms-rand.t ../Games-ABC_Path-Generator/lib/Games/ABC_Path/Generator/FinalLayoutObj.pm

test:
	firefox abc-path-test.html
