#!/usr/bin/perl

use strict;
use warnings;

use Games::ABC_Path::Generator;

use Getopt::Long;

my $seed = 24;
my $mode = 'final';
if (!GetOptions(
        'seed=i' => \$seed,
        'mode=s' => \$mode,
    ))
{
    die "Could not get options for program!";
}

my $gen = Games::ABC_Path::Generator->new({ seed => $seed, });

if ($mode eq 'final')
{
    print $gen->calc_final_layout()->as_string({});
}
elsif ($mode eq 'riddle')
{
    my $riddle = $gen->calc_riddle();

    my $layout_string = $riddle->get_final_layout_as_string({});
    
    my $riddle_string = $riddle->get_riddle_v1_string;

    print sprintf(
        "ABC Path Solver Layout Version 1:\n%s\nSolution:\n%s",
        $riddle_string, $layout_string,
    );
}
